services:
  app:
    build: .
    ports:
      - 3001:3001
    links:
      - redis
    environment:
      DATABASE_URI: "mysql+pymysql://root:secret@192.168.80.137:3306/test"
    depends_on:
      - redis

  worker:
    build:
      context: .
    working_dir: /app/src
    entrypoint: celery
    command: -A scanner.celery_app worker --loglevel=info
    environment:
      DATABASE_URI: "mysql+pymysql://root:secret@192.168.80.137:3306/test"
    links:
      - redis
    depends_on:
      - app
      - redis

  redis:
    image: redis:latest
    hostname: redis